/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**********************************************************************************************************************
 * Include files
**********************************************************************************************************************/
#include"main.h"

/*********************************************** end of Include files ************************************************/

/**********************************************************************************************************************
 * PRAGMAS
**********************************************************************************************************************/

/******************************************** end of PRAGMAs *********************************************************/

/**********************************************************************************************************************
 * Global Variables
**********************************************************************************************************************/
/* Flags used to indicate updated data is received*/


/*************************************** end of Global Variables ****************************************************/

/*********************************************************************************************************************
 * Static Function Prototypes
*********************************************************************************************************************/

/***************************************** end of Static Function Prototypes ****************************************/

/*********************************************************************************************************************
 * Function Definitions
*********************************************************************************************************************/

/*********************************************************************************************************************
* Function name      :
* Description        :
*
* Passing Arguments  : None
* Function Called By :
* Return value       : None
*********************************************************************************************************************/
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay_us(uint32_t usec)
{
    for(uint32_t i = 0; i < usec * 8; i++) {
        __asm__("nop");
    }
}
void delay_ms(uint32_t msec)
{
    for(uint32_t i = 0; i < msec; i++) {
        delay_us(1000);
    }
}
int main(void)
{

	GPIO_Handle_t gpioLed ;
	GPIO_Handle_t gpioSwitch;

	gpioSwitch.pGPIOx = GPIOC;
	gpioSwitch.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	gpioSwitch.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_IN;
	gpioSwitch.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FAST;
	gpioSwitch.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;



	gpioLed.pGPIOx = GPIOA;
	gpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	gpioLed.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_OUT;
	gpioLed.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FAST;
	gpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&gpioSwitch);
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&gpioLed);
	while(1U)
	{
		if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13)== GPIO_PIN_RESET)
		{
			/* Function call to Off LED */
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, GPIO_PIN_RESET);
		}
		else if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13)== GPIO_PIN_SET)
		{
			/* Function call to Off LED */
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, GPIO_PIN_SET);
		}
	}

}

/************************************************ end of Function Definitions ****************************************/

/************************************************ end of main.c ***************************************************/




