/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**********************************************************************************************************************
 * Include files
**********************************************************************************************************************/
#include"main.h"

/*********************************************** end of Include files ************************************************/

/**********************************************************************************************************************
 * PRAGMAS
**********************************************************************************************************************/

/******************************************** end of PRAGMAs *********************************************************/

/**********************************************************************************************************************
 * Global Variables
**********************************************************************************************************************/
/* Flags used to indicate updated data is received*/


/*************************************** end of Global Variables ****************************************************/

/*********************************************************************************************************************
 * Static Function Prototypes
*********************************************************************************************************************/

/***************************************** end of Static Function Prototypes ****************************************/

/*********************************************************************************************************************
 * Function Definitions
*********************************************************************************************************************/

/*********************************************************************************************************************
* Function name      :
* Description        :
*
* Passing Arguments  : None
* Function Called By :
* Return value       : None
*********************************************************************************************************************/
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay_us(uint32_t usec)
{
    for(uint32_t i = 0; i < usec * 8; i++) {
        __asm__("nop");
    }
}
void delay_ms(uint32_t msec)
{
    for(uint32_t i = 0; i < msec; i++) {
        delay_us(1000);
    }
}
int main(void)
{
	uint32_t pulseWidth = RESET;
	float distance = RESET;
	GPIO_Handle_t gpioLed ;
	GPIO_Handle_t GpioTrig;
	GPIO_Handle_t GpioEcho;

	GpioTrig.pGPIOx = GPIOC;
	GpioTrig.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GpioTrig.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioTrig.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioTrig.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioTrig.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GpioEcho.pGPIOx = GPIOC;
	GpioEcho.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_1;
	GpioEcho.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GpioEcho.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioEcho.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	gpioLed.pGPIOx = GPIOA;
	gpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	gpioLed.GPIO_PinConfig.GPIO_PinMode   = GPIO_MODE_OUT;
	gpioLed.GPIO_PinConfig.GPIO_PinSpeed  = GPIO_SPEED_FAST;
	gpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	gpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&GpioTrig);
	GPIO_Init(&GpioEcho);
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&gpioLed);
	while(1U)
	{

		GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_0, GPIO_PIN_SET);
		delay_us(10);
		GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_0, GPIO_PIN_RESET);
		while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_1) == 0);
		pulseWidth = RESET;
		while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_1) == 1) {
			pulseWidth++;
			delay_us(1);
		}
		distance = (pulseWidth * 0.0343f) / 2;
		if(distance < 20.0f) {
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, GPIO_PIN_SET);
		}
		else {
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, GPIO_PIN_RESET);
		}
		delay_ms(50);
	}

}

/************************************************ end of Function Definitions ****************************************/

/************************************************ end of main.c ***************************************************/




